http://localhost:3000/api/busca-nome?nome=asd

###

http://localhost:3000/api/produtos/novo
body:{"produto":{"nome":"teste","preco":30.99}}

###
http://localhost:3000/api/usuarios/novo
body:{"pessoa":{"nome":"teste","email":"breno@123"}}


